_target_: models.variational_module.MNISTModule

num_anchor: 10
batch_size: 1024
layer_size: 16
hidden_size: 10
use_relative_space: False

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10