_target_: models.variational_module.MNISTModule

num_anchor: 500
batch_size: 1024
layer_size: 32
hidden_size: 500
use_relative_space: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10