# 25, 46
variational: False
enc_relative_space: False
dec_relative_space: False
use_relative_space: False
enc_seed: 24
dec_seed: 42
tag: ${enc_relative_space}${dec_relative_space}_${enc_seed}_${dec_seed}